baseurl: "/"
languageCode: "en-us"
title: "Bo Shao's Journal"
theme: "hugo-ivy"
ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"
  - "\\.tmp$"
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

description: "Explore Bo's world of insights and stories."

permalinks:
  note: "/notes/:year/:month/:day/:slug/"
  post: "/articles/:year/:month/:day/:slug/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Notes"
      url: "/notes/"
      weight: 3
    - name: "Articles"
      url: "/articles/"
      weight: 4
    - name: "Categories"
      url: "/categories/"
      weight: 5
    - name: "Tags"
      url: "/tags/"
      weight: 6
    - name: "Subscribe"
      url: "/index.xml"
      weight: 7

params:
  description: "Welcome to Bo Shao's Journal - a space for knowledge and discovery."
  footer: "&copy; 2024 Bo Shao | Built with [Hugo](https://gohugo.io) | Follow me on [GitHub](https://github.com/bo-shao)"
  highlightjsLang:
    - "latex"
    - "python"
    - "yaml"
  highlightjsTheme: "atom-one-dark"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
