baseurl: /
languageCode: en-us
title: Bo Shao
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About Me"
      url: "/about me/"
      weight: 2
    - name: "Publications"
      url: "/bublications/"
      weight: 3
    - name: "Projects"
      url: "/projects/"
      weight: 4
    - name: "Honors & Awards"
      url: "honors & awards"
      weight: 5
    - name: "Hobbies"
      url: "hobbies"
      weight: 6
      
      
      
params:
  description: "Welcome to Bo's planet."
  footer: "&copy; [Bo Shao](https://boshao.netlify.app) {Year} | [Github](https://github.com/boshao321)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
