baseurl: /
languageCode: en-us
title: Bo Shao
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Research"
      url: "/research/"
      weight: 3
    - name: "Publications"
      url: "/publications/"
      weight: 4
    - name: "Honors"
      url: "/honors/"
      weight: 5
    - name: "Hobbies"
      url: "/hobbies/"
      weight: 6
    - name: "Notes"
      url: "/note/"
      weight: 7
      
      
      
params:
  description: "Welcome to Bo's planet."
  footer: "&copy; [Bo Shao](https://boshao.netlify.app) {Year} | [LinkedIn](https://www.linkedin.com/in/boshao321/) | [ResearchGate](https://www.researchgate.net/profile/Bo-Shao-15) | [ORCID](https://orcid.org/0000-0002-3360-8886)"
  highlightjsLang: ["latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
